### ISSUE TITLE
exception dumps stack traces

### ISSUE THREAD

**Issue by pjanzen** [logstash-plugins/logstash-filter-dissect#54]
During creation of an dissect filter I ran into the below error.

- Version: 5.3.1
- Operating Sytem: Linux (Ubuntu)
- Sample Data: I dont have sample data as it trows an error.

```
if [message] =~ /^core/ {
  dissect {
    mapping => {
      "message" => "%{} %{message}"
    }
    add_field => { "core_message" => "true" }
  }
  if [message] =~ /^id/ {
    dissect {
      mapping => {
        "message" => "id=%{imp_id} %{message}"
      }
    }
  }
  if [message] =~ /^wf/ {
    dissect {
      mapping => {
        "message" => "wf=%{imp_wf} msg=%{message}"
      }
    }
  }
  if [message] =~ /logid/ {
    dissect {
      mapping => {
        "message" => "logid=%{imp_logid} ip=%{imp_ip} revdns=%{imp_revdns} %{message}"
      }
    }
  }
  if [message] =~ /canrelay/ {
    dissect {
      mapping => {
        "message" => "canrelay=%{imp_canrelay} action=%{imp_action}"
      }
    }
  }
  if [message] =~ /csi-result-ip/ {
    dissect {
      mapping => {
        "message" => "csi-result-ip=%{imp_csi-result-ip} action=%{imp_action}"
      }
    }
  }
  if [message] =~ /migstatus/ {
    dissect {
      mapping => {
        "message" => "cmigstatus=%{imp_migstatus} rcpt=%{imp_rcpt} mainmail=%{imp_mainmail} action=%{imp_action}"
      }
    }
  }
  if [message] =~ /^rcpt/ {
    if [message] =~ /action/ {
      dissect {
        mapping => {
          "message" => "rcpt=%{imp_rcpt} mainmail=%{imp_mainmail} domaintype=%{imp_domaintype} AV=%{imp_av} AS=%{imp_as} mailuserstatus=%{imp_mailuserstatus} action=%{imp_action}"
        }
      }
    } else {
      dissect {
        mapping => {
          "message" => "rcpt=%{imp_rcpt} mainmail=%{imp_mainmail} domaintype=%{imp_domaintype} AV=%{imp_av} AS=%{imp_as} mailuserstatus=%{imp_mailuserstatus}"
        }
      }
    }
  }
  # End core messages
} else {
  dissect {
    mapping => {
      "message" => "%{} %{message}"
    }
  }
  if [message] =~ /^id/ {
    dissect {
      mapping => {
        "message" => "id=%{imp_id} action=%{imp_action} wf=%{imp_wf} ip=%{imp_ip} from=%{imp_from} to=%{imp_to} %{message}"
      }
    }
    if [message] =~ /size/ {
      dissect {
        mapping => {
          "message" => "size=%{imp_size} filters=%{imp_filters}"
        }
      }
    } else if [message] =~ /filters/ {
      dissect {
        mapping => {
          "message" => "filters=%{imp_filters}"
        }
      }
    }
  } else if [message] =~ /^sid/ {
    dissect {
      mapping => {
        "message" => "sid=%{imp_sid} ip=%{imp_ip} action=%{imp_action} wf=%{imp_wf} smpt=%{imp_smtp} %{message}"
      }
    }
  }

```

Stacktrace produced:

```
Exception in thread "[main]>worker15" java.lang.ArrayIndexOutOfBoundsException: 0
    	at org.logstash.dissect.DissectorErrorUtils.backtrace(DissectorErrorUtils.java:16)
    	at org.logstash.dissect.JavaDissectorLibrary$RubyDissect.logException(JavaDissectorLibrary.java:209)
    	at org.logstash.dissect.JavaDissectorLibrary$RubyDissect.dissect(JavaDissectorLibrary.java:122)
    	at org.logstash.dissect.JavaDissectorLibrary$RubyDissect.dissect_multi(JavaDissectorLibrary.java:132)
    	at org.logstash.dissect.JavaDissectorLibrary$RubyDissect$INVOKER$i$2$0$dissect_multi.call(JavaDissectorLibrary$RubyDissect$INVOKER$i$2$0$dissect_multi.gen)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
    	at rubyjit.LogStash::Filters::Dissect$$multi_filter_1131382988356ee038e0c1769e4d4113e6c62a5c1442407170.__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.8/lib/logstash/filters/dissect.rb:184)
    	at rubyjit.LogStash::Filters::Dissect$$multi_filter_1131382988356ee038e0c1769e4d4113e6c62a5c1442407170.__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.8/lib/logstash/filters/dissect.rb)
    	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at rubyjit.LogStash::FilterDelegator$$multi_filter_9185c86df6161fe7ec4d7ab39bf5c16f36fd54611442407170.__file__(/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:42)
    	at rubyjit.LogStash::FilterDelegator$$multi_filter_9185c86df6161fe7ec4d7ab39bf5c16f36fd54611442407170.__file__(/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb)
    	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    	at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
    	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
    	at org.jruby.runtime.Block.yield(Block.java:142)
    	at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
    	at org.jruby.RubyArray.each(RubyArray.java:1613)
    	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
    	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.RubyProc.call19(RubyProc.java:281)
    	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    	at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
    	at org.jruby.runtime.Block.yield(Block.java:142)
    	at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
    	at org.jruby.RubyArray.each(RubyArray.java:1613)
    	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
    	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.RubyProc.call19(RubyProc.java:281)
    	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    	at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
    	at org.jruby.runtime.Block.yield(Block.java:142)
    	at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
    	at org.jruby.RubyArray.each(RubyArray.java:1613)
    	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
    	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.RubyProc.call19(RubyProc.java:281)
    	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    	at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
    	at org.jruby.runtime.Block.yield(Block.java:142)
    	at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
    	at org.jruby.RubyArray.each(RubyArray.java:1613)
    	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
    	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.RubyProc.call19(RubyProc.java:281)
    	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    	at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at rubyjit.LogStash::Pipeline$$filter_batch_e0d70a513c9b572e72031cc1bba279d4ffc82a801442407170.block_0$RUBY$__file__(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:353)
    	at rubyjit$LogStash::Pipeline$$filter_batch_e0d70a513c9b572e72031cc1bba279d4ffc82a801442407170$block_0$RUBY$__file__.call(rubyjit$LogStash::Pipeline$$filter_batch_e0d70a513c9b572e72031cc1bba279d4ffc82a801442407170$block_0$RUBY$__file__)
    	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:159)
    	at org.jruby.runtime.CompiledBlock19.call(CompiledBlock19.java:87)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.RubyProc.call19(RubyProc.java:281)
    	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
    	at rubyjit.LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1442407170.block_0$RUBY$__file__(/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:201)
    	at rubyjit$LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1442407170$block_0$RUBY$__file__.call(rubyjit$LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1442407170$block_0$RUBY$__file__)
    	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
    	at org.jruby.runtime.Block.yield(Block.java:142)
    	at org.jruby.RubyHash$13.visit(RubyHash.java:1355)
    	at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
    	at org.jruby.RubyHash.visitAll(RubyHash.java:634)
    	at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1306)
    	at org.jruby.RubyHash.each_pairCommon(RubyHash.java:1351)
    	at org.jruby.RubyHash.each19(RubyHash.java:1342)
    	at org.jruby.RubyHash$INVOKER$i$0$0$each19.call(RubyHash$INVOKER$i$0$0$each19.gen)
    	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    	at rubyjit.LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1442407170.__file__(/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:200)
    	at rubyjit.LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1442407170.__file__(/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb)
    	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
    	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
    	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
    	at rubyjit.LogStash::Pipeline$$filter_batch_e0d70a513c9b572e72031cc1bba279d4ffc82a801442407170.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352)
    	at rubyjit.LogStash::Pipeline$$filter_batch_e0d70a513c9b572e72031cc1bba279d4ffc82a801442407170.__file__(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb)
    	at rubyjit.LogStash::Pipeline$$filter_batch_e0d70a513c9b572e72031cc1bba279d4ffc82a801442407170.__file__(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb)
    	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
    	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
    	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
    	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
    	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
    	at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
    	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    	at org.jruby.runtime.Block.call(Block.java:101)
    	at org.jruby.RubyProc.call(RubyProc.java:300)
    	at org.jruby.RubyProc.call(RubyProc.java:230)
    	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by guyboertje** [comment]
@pjanzen 
I see that this error occurred when using `logstash-filter-dissect-1.0.8`. See the changelog...
https://github.com/logstash-plugins/logstash-filter-dissect/blob/master/CHANGELOG.md

There were significant bug fixes in v 1.1.1 and v1.1.4. Please upgrade to v 1.1.4.

I am closing this issue. If after the upgrade you still experience this fault please create a new issue, but **NOTE** that this is hard to debug this because I can't figure out which dissect is at fault and what the `message` field's value is at that time.
